# Site settings
title: Janne Cederberg
headers-dir: "/img/headers"
panoramas-dir: "/img/panoramas"
header-img: "bg-home.jpg"
header-img-mobile: "bg-home_640px.jpg"
email: janne.cederberg@gmail.com
description: "The founder of Opetus.tv, a site like Khan Academy but with Finnish content based on Finnish curriculum, thousands of videos and no outside funding."
baseurl: ""
url: "http://jannecederberg.fi"

twitter_username: jannecederberg
linkedin_url: https://www.linkedin.com/in/jannecederberg
github_username:  jannecederberg
facebook_username: janne.cederberg
phone_number: "+358503785215"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
